Bumped SDK version, implemented Navigation Component
Sitecore/xmcloud-starter-aspnetcore pull request #8
Opened 2024-09-11 05:38 UTC by robearlam

This PR increases the version of the SDK used to v0.0.9 - in order to leverage the new `CustomComponent` binding functionality.

This functionality is used to implement the `Navigation` component included here.

## Description / Motivation
Implementation of the Navigation component now means that the Skate Park template is now completely supported.

## Terms

- [x] I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md).

2024-09-13 07:25 UTC, sc-ivanlieckens requested changes

2024-09-13 07:25 UTC, sc-ivanlieckens commented on headapps/aspnet-core-starter/Models/Navigation/NavigationTitle.cs
Where is this one used?

2024-09-16 04:50 UTC, robearlam commented on headapps/aspnet-core-starter/Models/Navigation/NavigationTitle.cs
This wasn't needed in the end, remove from the project.

2024-10-02 06:59 UTC, sc-ivanlieckens approved these changes

2024-10-02 06:59 UTC, merged